[package]
name = "php-5x"
version = "0.1.0"
authors = ["Paweł Chojnacki <pawel.chcki@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
proc-macro2 = "1.0"
syn = "1.0"
quote = "1.0"
php-all-sys = "0.0.1"
php-test-macros = { path = "test-macros" }
